codecov:
  require_ci_to_pass: yes

ignore:
  - "src/muse_as_service/utils.py"
  - "src/muse_as_service/database/add_user.py"
  - "src/muse_as_service/database/remove_user.py"

coverage:
  status:
    project:
      default: false
      source:
        paths:
          - "src/"
        target: 90%
    patch: off
