# This workflow will install Python dependencies and run codecov
# https://github.com/codecov/codecov-action#example-workflowyml-with-codecov-action

name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Launch Flask app
      run: |
        ./models/download_muse.sh
        python app.py &
      env:
        SECRET_KEY: test
        JWT_SECRET_KEY: test
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
